import Foundation

/// Presentation-only translations. Persisted option titles and control identifiers stay unchanged.
enum L10n {
    static var isEnglish: Bool { UserDefaults.standard.string(forKey: "settings.language") == "English" }

    static func text(_ source: String) -> String {
        isEnglish ? (english[source] ?? source) : source
    }

    /// A translated `String(format:)` template: the key keeps its `%@`/`%d` slots.
    static func format(_ source: String, _ arguments: CVarArg...) -> String {
        String(format: text(source), arguments: arguments)
    }

    /// The worker reports in English; the ones the user reads in the UI are known
    /// here by their exact text (src/services/live_worker_service.py). Others pass as is.
    static func workerMessage(_ message: String) -> String {
        workerMessages[message].map(text) ?? message
    }

    private static let workerMessages: [String: String] = [
        "No final transcript events are available yet": "В записи ещё нет распознанных фраз — спросите после первой.",
        "Question is required": "Введите вопрос.",
        "LLM settings are required": "LLM не настроена.",
    ]

    private static let english: [String: String] = [
        "Обработка": "Processing",
        "Результат обработки": "Processing result",
        "Результат": "Result",
        "Журнал": "History",
        "Настройки": "Settings",
        "Загрузите аудио или видео и настройте параметры.": "Upload audio or video and adjust the settings.",
        "Плеер, транскрипция и экспорт обработанного файла.": "Playback, transcription and export of the processed file.",
        "Захват в реальном времени и мгновенная транскрипция.": "Real-time capture and instant transcription.",
        "Постобработка транскрипций и работа с пользовательскими промптами.": "Post-process transcripts and work with custom prompts.",
        "Рабочая документация и примеры запросов внутри приложения.": "Documentation and request examples within the app.",
        "История обработок, статусов и готовых результатов.": "Processing history, statuses and completed results.",
        "Параметры приложения, обработки, моделей и путей хранения.": "App, processing, model and storage settings.",
        "Транскрибация аудио и видео": "Audio and video transcription",
        "Локально. Быстро. Точно.": "Local. Fast. Accurate.",
        "Поиск": "Search",
        "Поиск разделов": "Search pages",
        "Переключить тему": "Switch theme",
        "Переключить язык": "Switch language",
        "Загрузка файлов": "Upload files",
        "Перетащите сюда аудио или видео": "Drop audio or video here",
        "Перетащите сюда аудио, видео или папку": "Drop audio, video or a folder here",
        ".wav, .mp3, .m4a, .mp4, .mov, .mkv · папка сканируется целиком": ".wav, .mp3, .m4a, .mp4, .mov, .mkv · folders are scanned recursively",
        "Выбрать файлы": "Choose files",
        "Ссылка на медиа": "Media URL",
        "Загрузить": "Download",
        "Отмена": "Cancel",
        "Загрузка медиа": "Downloading media",
        "Вставьте ссылку http:// или https://. Медиа будет загружено в кэш приложения и добавлено к выбранным файлам.": "Paste an http:// or https:// URL. Media will be downloaded to the app cache and added to the selected files.",
        "Введите корректную ссылку http:// или https:// с именем сервера.": "Enter a valid http:// or https:// URL with a host name.",
        "Загрузчик работает. Точный прогресс недоступен. После завершения файл появится в списке выбранных.": "The downloader is running. Exact progress is unavailable. The file will appear in the selection when the download finishes.",
        "Загрузка отменена.": "Download cancelled.",
        "Не удалось запустить Python для загрузки медиа.": "Could not start Python to download media.",
        "Не удалось загрузить медиа. Проверьте ссылку и Python-окружение проекта: нужны yt-dlp и зависимости requirements.txt.": "Could not download media. Check the URL and the project's Python environment: yt-dlp and the dependencies in requirements.txt are required.",
        "Код завершения": "Exit code",
        "Загрузчик не вернул список файлов. Проверьте Python-окружение проекта.": "The downloader did not return a file list. Check the project's Python environment.",
        "Загрузчик вернул недоступный файл.": "The downloader returned an inaccessible file.",
        "GIGAAM_PROJECT_ROOT должен указывать на папку проекта с app.py и src/utils/media_downloader.py.": "GIGAAM_PROJECT_ROOT must point to the project folder containing app.py and src/utils/media_downloader.py.",
        "Не найдены файлы загрузчика. Запустите клиент из папки проекта или задайте GIGAAM_PROJECT_ROOT.": "Downloader files were not found. Launch the client from the project folder or set GIGAAM_PROJECT_ROOT.",
        "GIGAAM_PYTHON должен указывать на исполняемый Python с зависимостями проекта.": "GIGAAM_PYTHON must point to an executable Python interpreter with the project's dependencies.",
        "Python не найден. Подготовьте .venv с зависимостями проекта или задайте GIGAAM_PYTHON. Автоматическая установка не выполняется.": "Python was not found. Prepare .venv with the project's dependencies or set GIGAAM_PYTHON. Nothing is installed automatically.",
        "Настройки обработки": "Processing settings",
        "Режим": "Mode",
        "Движок": "Engine",
        "Язык": "Language",
        "Кол-во спикеров": "Speaker count",
        "Авто (рекомендуется)": "Auto (recommended)",
        "Точный": "Accurate",
        "Быстрый": "Fast",
        "Русский": "Russian",
        "Авто": "Auto",
        "Выбранные файлы": "Selected files",
        "Очистить": "Clear",
        "Убрать файл": "Remove file",
        "Файл": "File",
        "Состояние": "State",
        "Файлы не выбраны. Добавьте аудио или видео.": "No files selected. Add audio or video.",
        "Папка сохранения результатов": "Output folder",
        "Выберите папку": "Choose a folder",
        "Изменить": "Change",
        "Форматы вывода": "Output formats",
        "Текст (.txt)": "Text (.txt)",
        "Таймкоды": "Timestamps",
        "Диаризация (.txt)": "Diarization (.txt)",
        "Диар. + таймкоды": "Diar. + timestamps",
        "Sortformer определяет спикеров автоматически (до 4). Pyannote и ONNX принимают известное число спикеров.": "Sortformer detects speakers automatically (up to 4). Pyannote and ONNX accept a known speaker count.",
        "Sortformer определяет спикеров автоматически (до 4); ручное значение доступно для pyannote и ONNX.": "Sortformer detects speakers automatically (up to 4); a manual count is available for pyannote and ONNX.",
        "Настройки субтитров": "Subtitle settings",
        "Строк в блоке": "Lines per block",
        "Символов": "Characters",
        "Разбивать по предложениям": "Split by sentence",
        "Запустить обработку": "Start processing",
        "Рабочий сервис обработки не подключён.": "The processing service is not connected.",
        "Файл не выбран": "No file selected",
        "Нет обработанного файла  •  —  •  —": "No processed file  •  —  •  —",
        "Воспроизвести": "Play",
        "Назад на 10 секунд": "Back 10 seconds",
        "Вперёд на 10 секунд": "Forward 10 seconds",
        "Транскрипция": "Transcript",
        "Диаризация": "Diarization",
        "Резюме": "Summary",
        "Транскрипция появится после обработки файла.": "The transcript will appear after processing a file.",
        "Время": "Time",
        "Спикер": "Speaker",
        "Текст": "Text",
        "Полезное": "Tools",
        "Действия": "Actions",
        "Скачать всё": "Download all",
        "Копировать текст": "Copy text",
        "Скачать SRT": "Download SRT",
        "Скачать Markdown": "Download Markdown",
        "Скачать JSON": "Download JSON",
        "Ключевые темы": "Key topics",
        "Темы ещё не определены.": "No topics identified yet.",
        "Краткое содержание": "Summary",
        "Содержание появится после анализа фактической транскрипции.": "A summary will appear after analyzing the actual transcript.",
        "Источник аудио": "Audio source",
        "Не подключён": "Not connected",
        "Микрофон": "Microphone",
        "Системный звук": "System audio",
        "Выкл.": "Off",
        "Включено": "On",
        "Выключено": "Off",
        "Выключен": "Off",
        "Записывать микрофон": "Record microphone",
        "Записывать системный звук": "Record system audio",
        "Запись": "Recording",
        "Запись не начата": "Recording not started",
        "Начать запись": "Start recording",
        "Остановить запись": "Stop recording",
        "Приостановить запись": "Pause recording",
        "Параметры": "Parameters",
        "Язык аудио": "Audio language",
        "Нет фрагментов. Начните запись.": "No segments yet. Start recording.",
        "По умолчанию": "Default",
        "Оценка вживую": "Live estimate",
        "После остановки": "After stop",
        "Уровень сигнала": "Signal level",
        "Папка сессий": "Sessions folder",
        "Вопрос ассистенту по текущей записи": "Ask the assistant about this recording",
        "Спросить": "Ask",
        "Ответ ассистента": "Assistant answer",
        "Ассистент отвечает…": "The assistant is answering…",
        "Ошибка LLM: ": "LLM error: ",
        "Не удалось начать запись": "Could not start recording",
        "Дождитесь завершения текущей обработки.": "Wait for the current processing to finish.",
        "Укажите абсолютный путь к папке сессий.": "Provide an absolute path to the sessions folder.",
        "Запрос доступа к микрофону…": "Requesting microphone access…",
        "Нет доступа к микрофону": "No microphone access",
        "Разрешите доступ в Системных настройках → Конфиденциальность и безопасность → Микрофон.": "Allow access in System Settings → Privacy & Security → Microphone.",
        "Нет доступа к системному звуку": "No system audio access",
        "Разрешите «Запись экрана и системного звука» для GigaAMLiquid в Системных настройках → Конфиденциальность и безопасность.": "Allow “Screen & System Audio Recording” for GigaAMLiquid in System Settings → Privacy & Security.",
        "Запуск…": "Starting…",
        "Остановка…": "Stopping…",
        "Идёт запись": "Recording",
        "Пауза": "Paused",
        "Захват не удался": "Capture failed",
        "Источник недоступен: ": "Source unavailable: ",
        "Сессия сохранена: ": "Session saved: ",
        "Сессия сохранена": "Session saved",
        "Загрузка модели распознавания… Запись начнётся, когда она будет готова.": "Loading the recognition model… Recording starts once it is ready.",
        "Сессия остановлена с ошибкой: ": "Session stopped with an error: ",
        "Сохранено в ": "Saved to ",
        "Запись в ": "Recording to ",
        "Сохраняется в ": "Saving to ",
        "Каждая запись сохраняется в свою папку ГГГГ-ММ-ДД_ЧЧ-ММ-СС: транскрипт, субтитры и аудио.": "Each recording is saved to its own YYYY-MM-DD_HH-MM-SS folder: transcript, subtitles and audio.",
        "Открыть папку сессии": "Open session folder",
        "Не удалось открыть папку": "Could not open the folder",
        "Выбрать": "Choose",
        "Live-сессия прервана.": "Live session interrupted.",
        "Worker не успевает обрабатывать звук; фрагмент пропущен.": "The worker cannot keep up with the audio; a chunk was dropped.",
        "Микрофон недоступен.": "The microphone is unavailable.",
        "Микрофон отключён.": "The microphone was disconnected.",
        "Нет доступного дисплея для захвата системного звука.": "No display is available for system audio capture.",
        "Дождитесь завершения live-сессии.": "Wait for the live session to finish.",
        "Импорт медиа, распознавание, live-захват и LLM используют встроенные Python-сервисы проекта; звук захватывает само приложение.": "Media import, recognition, live capture and LLM use the project's bundled Python services; audio is captured by the app itself.",
        "Исходный текст": "Source text",
        "Выбрать файл с транскриптом": "Choose transcript file",
        "Провайдер": "Provider",
        "Локальный": "Local",
        "Модель": "Model",
        "Транскрипция · можно вставить текст": "Transcript · paste text here",
        "Исходная транскрипция": "Source transcript",
        "Текст и параметры сохраняются на этом Mac.": "Text and settings are saved on this Mac.",
        "Шаблоны": "Templates",
        "Сжать текст в тезисы": "Condense into key points",
        "Извлечение задач": "Extract tasks",
        "Выделить action items": "Identify action items",
        "Свой промпт": "Custom prompt",
        "Использовать инструкцию": "Use your instruction",
        "Пользовательский промпт": "Custom prompt",
        "Ответа пока нет. Здесь появится результат запроса к выбранному провайдеру.": "No response yet. Results from the selected provider will appear here.",
        "Адрес, ключ и пути к CLI-провайдерам — в Настройки → LLM.": "API address, key and CLI provider paths live in Settings → LLM.",
        "Отменить запрос": "Cancel request",
        "Сохранить .md": "Save .md",
        "Запрос отправлен…": "Request sent…",
        "Ожидание ответа провайдера…": "Waiting for the provider…",
        "Готово.": "Done.",
        "Готово. Сохранено: ": "Done. Saved: ",
        "Запрос отменён.": "Request cancelled.",
        "Не удалось запустить LLM": "Could not start the LLM request",
        "Выберите файл с транскриптом или вставьте текст.": "Choose a transcript file or paste text.",
        "Выберите шаблон или введите пользовательский промпт.": "Pick a template or enter a custom prompt.",
        "LLM не настроена": "LLM is not configured",
        "Temperature должно быть числом в диапазоне 0..2": "Temperature must be a number between 0 and 2",
        "Укажите API URL в Настройки → LLM": "Set the API URL in Settings → LLM",
        "Укажите API Key в Настройки → LLM": "Set the API key in Settings → LLM",
        "Укажите модель": "Specify a model",
        "Укажите команду для провайдера «Другое» в Настройки → LLM": "Set a command for the “Other” provider in Settings → LLM",
        "Не удалось сохранить API Key": "Could not save the API key",
        "Не удалось сохранить": "Could not save",
        "Аргументы": "Arguments",
        "Другое (команда)": "Other (command)",
        "Провайдер постобработки и вопросов ассистенту в Live. API — OpenAI-совместимый или Anthropic адрес; остальные — локальные CLI.": "Provider for post-processing and Live assistant questions. API is an OpenAI-compatible or Anthropic endpoint; the rest are local CLIs.",
        "Ключ хранится в Связке ключей. CLI-провайдеры запускаются Python-сервисом проекта с указанными путями и аргументами.": "The key is stored in the Keychain. CLI providers are launched by the project's Python service with the given paths and arguments.",
        "Копировать": "Copy",
        "Примеры запросов": "Request examples",
        "Статус API": "API status",
        "○  Не подключён": "○  Not connected",
        "http://127.0.0.1:8000  •  адрес примера": "http://127.0.0.1:8000  •  example address",
        "Скопировать URL": "Copy URL",
        "Открыть документацию": "Open documentation",
        "Копировать пример": "Copy example",
        "Пример запроса, не ответ сервера. Этот клиент не запускает API.": "A request example, not a server response. This client does not start the API.",
        "Документация": "Documentation",
        "Быстрый старт": "Quick start",
        "Эндпоинты": "Endpoints",
        "Примеры": "Examples",
        "Форматы ответов": "Response formats",
        "Скачать OpenAPI (JSON)": "Download OpenAPI (JSON)",
        "Схема доступна после подключения API.": "The schema is available after connecting the API.",
        "История": "History",
        "Все": "All",
        "Успешные": "Successful",
        "Ошибки": "Errors",
        "В обработке": "Processing",
        "Ошибка": "Error",
        "В истории пока нет записей.": "No history entries yet.",
        "Поиск по истории": "Search history",
        "Длительность": "Duration",
        "Статус": "Status",
        "Дата": "Date",
        "История обработок: записей нет": "Processing history: no entries",
        "История пуста. Завершённые обработки появятся здесь.": "History is empty. Completed jobs will appear here.",
        "0 записей": "0 entries",
        "Общие": "General",
        "Модели": "Models",
        "Аудио": "Audio",
        "Пути": "Paths",
        "О приложении": "About",
        "Язык и оформление приложения. Изменения сохраняются автоматически.": "App language and appearance. Changes are saved automatically.",
        "Язык интерфейса": "Interface language",
        "Тема": "Theme",
        "Системная": "System",
        "Светлая": "Light",
        "Тёмная": "Dark",
        "Модель распознавания и устройство вычислений.": "Speech recognition model and compute device.",
        "Устройство": "Device",
        "Fallback на CPU": "Fall back to CPU",
        "Разбиение транскрипции и оформление субтитров.": "Transcript segmentation and subtitle formatting.",
        "Символов в строке": "Characters per line",
        "Показывать спикера": "Show speaker",
        "Разделение речи по спикерам и доступ к моделям Hugging Face.": "Separate speech by speaker and access Hugging Face models.",
        "Движок диаризации": "Diarization engine",
        "Не настроен": "Not configured",
        "Параметры аудиосигнала для обработки.": "Audio signal settings for processing.",
        "Частота дискретизации": "Sample rate",
        "Отдельный REST API запускается из api.py. Нативный клиент не запускает сервер и не проверяет его доступность.": "The separate REST API starts from api.py. The native client does not start the server or check its availability.",
        "Адрес в примерах · не настройка подключения": "Example address · not a connection setting",
        "Для запросов требуется заголовок Authorization: Bearer <ключ> (X-API-Key принимается как устаревший вариант). Примеры Python, cURL и JavaScript доступны в разделе API основного меню.": "Requests require the Authorization: Bearer <key> header (X-API-Key is accepted as a legacy alternative). Python, cURL and JavaScript examples are available on the API page in the main menu.",
        "Хранение результатов и визуальные эффекты приложения.": "Result storage and app visual effects.",
        "Папка результатов": "Output folder",
        "Папка": "Folder",
        "Транскрибация русской речи из аудио и видео на базе GigaAM-v3.": "Russian speech transcription from audio and video, powered by GigaAM-v3.",
        "Релиз основного приложения": "Main application release",
        "Этот интерфейс — нативный клиент AppKit без отдельного номера релиза. Импорт медиа по ссылке использует загрузчик проекта. Распознавание речи и LLM пока не подключены.": "This interface is a native AppKit client without a separate release number. Media URL import uses the project's downloader. Speech recognition and LLM are not connected yet.",
        "Разработчики приложения": "Application developers",
        "Модель распознавания": "Speech recognition model",
        "Проект на GitHub": "Project on GitHub",
        "Общий прогресс": "Overall progress",
        "Нет активных задач": "No active jobs",
        "Не удалось открыть транскрипт": "Could not open transcript",
        "POST /v1/audio/transcriptions принимает multipart-поле file. Основные поля: model (whisper-1 и другие алиасы), response_format (json/text/srt/vtt/verbose_json/diarized_json), stream, timestamp_granularities[]. Расширения GigaAM: diarize, diarization_backend, num_speakers, asr_backend, onnx_provider, audio_preprocessing. Требуется заголовок Authorization: Bearer <ключ>.": "POST /v1/audio/transcriptions accepts the multipart field file. Main fields: model (whisper-1 and other aliases), response_format (json/text/srt/vtt/verbose_json/diarized_json), stream, timestamp_granularities[]. GigaAM extensions: diarize, diarization_backend, num_speakers, asr_backend, onnx_provider, audio_preprocessing. The Authorization: Bearer <key> header is required.",
        "Ответ возвращается синхронно, сразу в запросе. Формат задаётся response_format: json, text, srt, vtt, verbose_json или diarized_json. При stream=true json/verbose_json приходят по SSE: во время обработки — комментарии прогресса, дельты текста — после распознавания всего файла.": "The response is returned synchronously, in the request itself. The format is set by response_format: json, text, srt, vtt, verbose_json or diarized_json. With stream=true, json/verbose_json are delivered over SSE: progress comments during processing, text deltas after the whole file has been recognized.",
        "POST /v1/audio/transcriptions — распознать файл.\nGET /v1/models — доступные модели.\nGET /health — состояние сервиса.": "POST /v1/audio/transcriptions — transcribe a file.\nGET /v1/models — available models.\nGET /health — service health.",
        "Выберите Python, cURL или JavaScript слева. Кнопка «Копировать пример» копирует показанный код. Задайте свой API-ключ и путь к аудиофайлу.": "Choose Python, cURL or JavaScript on the left. Copy example copies the displayed code. Set your own API key and audio file path.",
        "Отдельный REST API запускается командой python api.py. REST API совместим с OpenAI Audio API: укажите base_url http://127.0.0.1:8000/v1 в любом клиенте OpenAI. Примеры на этой странице соответствуют POST /v1/audio/transcriptions.\n\nЭтот нативный клиент не запускает сервер и не проверял его доступность.": "The separate REST API starts with the command python api.py. The REST API is OpenAI Audio API-compatible: point any OpenAI client at base_url http://127.0.0.1:8000/v1. Examples on this page use POST /v1/audio/transcriptions.\n\nThis native client does not start the server and has not checked its availability.",
        "выбран, не обработан": "selected, not processed",
        "Ещё файлов: %d. Полный список — в подсказке.": "%d more files. See the tooltip for the full list.",
        "Субтитры SRT": "SRT subtitles",
        "данных пока нет. Сначала обработайте файл.": "no data yet. Process a file first.",
        "Ничего не найдено": "No results found",
        "Транскрипция и сохранённые файлы обработки.": "Transcript and saved processing files.",
        "Подготовка аудио": "Audio preprocessing",
        "Остановить после текущего файла": "Stop after the current file",
        "Остановка запрошена": "Stop requested",
        "Остановка после текущего файла.": "Stopping after the current file.",
        "Готовые файлы сохранены на диске.": "Generated files are saved on disk.",
        "Результат получен. Сохранённые файлы недоступны.": "Result received. Saved files are unavailable.",
        "Использовать в LLM": "Use in LLM",
        "Сохранённые файлы": "Saved files",
        "Нет файлов": "No files",
        "Открыть файл": "Open file",
        "Показать в Finder": "Show in Finder",
        "Доступны только фактические результаты. LLM-анализ и воспроизведение не подключены.": "Only actual results are available. LLM analysis and playback are not connected.",
        "Устройство и fallback выбирает backend. ONNX provider применяется только к ONNX. Язык определяется моделью.": "The backend selects the device and fallback. ONNX provider applies only to ONNX. The model determines the language.",
        "Метки спикеров добавляются автоматически при включённой диаризации.": "Speaker labels are added automatically when diarization is enabled.",
        "Pyannote требует токен и принятые лицензии моделей Hugging Face. Пустое поле использует HF_TOKEN из окружения.": "Pyannote requires a token and accepted Hugging Face model licenses. An empty field uses HF_TOKEN from the environment.",
        "Частоту 16000 Hz задаёт конвертер. auto — автоматическая подготовка, off — без неё, light — лёгкая обработка, denoise — шумоподавление.": "The converter sets 16000 Hz. auto — automatic preprocessing, off — none, light — light processing, denoise — noise reduction.",
        "Этот интерфейс — нативный клиент AppKit без отдельного номера релиза. Импорт медиа и распознавание речи используют Python-сервисы проекта. Live и LLM пока не подключены.": "This is a native AppKit client without a separate release number. Media import and speech recognition use the project's Python services. Live and LLM are not connected yet.",
        "Параметр задаёт рабочий сервис; отдельное управление недоступно.": "The processing service controls this setting; separate adjustment is unavailable.",
        "Журнал обработки": "Processing log",
        "Выберите файлы, доступную папку и хотя бы один формат.": "Choose files, a writable folder and at least one format.",
        "Настройки зафиксированы до завершения обработки. Навигация доступна.": "Settings are locked until processing finishes. Navigation remains available.",
        "Дождитесь завершения импорта медиа.": "Wait for media import to finish.",
        "Добавьте аудио или видео для начала обработки.": "Add audio or video to start processing.",
        "Укажите абсолютный путь к доступной папке результатов.": "Enter an absolute path to a writable output folder.",
        "Укажите абсолютный путь к доступной папке результатов или оставьте поле пустым.": "Enter an absolute path to a writable output folder or leave the field empty.",
        "Рядом с исходным файлом": "Next to the source file",
        "Пустое поле — результаты сохраняются в папку исходного файла.": "Leave it empty to save results in the source file's folder.",
        "Технические подробности для отчёта об ошибке:": "Technical details for a bug report:",
        "Выберите хотя бы один формат вывода.": "Select at least one output format.",
        "Не удалось начать обработку": "Could not start processing",
        "В очереди": "Queued",
        "Запуск распознавания…": "Starting transcription…",
        "Обработка остановлена. Готовые результаты сохранены.": "Processing stopped. Completed results have been saved.",
        "Обработка завершена. Результаты доступны в разделе «Результат».": "Processing complete. Open Result to view the outputs.",
        "Обработка завершена с ошибками. Подробности — в журнале обработки.": "Processing finished with errors. See the processing log for details.",
        "Не обработан: остановлено": "Not processed: stopped",
        "Не обработан": "Not processed",
        "Не обработан: ошибка": "Not processed: error",
        "Не удалось открыть файл": "Could not open file",
        "Файл результата больше недоступен.": "The output file is no longer available.",
        "Понятно": "OK",
        "О приложении GigaAM v3": "About GigaAM v3",
        "Скрыть GigaAM v3": "Hide GigaAM v3",
        "Скрыть остальные": "Hide Others",
        "Показать все": "Show All",
        "Завершить GigaAM v3": "Quit GigaAM v3",
        "Выбрать файлы…": "Choose Files…",
        "Ссылка на медиа…": "Media Link…",
        "Закрыть окно": "Close Window",
        "Правка": "Edit",
        "Отменить": "Undo",
        "Повторить": "Redo",
        "Вырезать": "Cut",
        "Вставить": "Paste",
        "Выделить всё": "Select All",
        "Окно": "Window",
        "Свернуть": "Minimize",
        "Масштабировать": "Zoom",
        "Все окна — на передний план": "Bring All to Front",
        "Справка": "Help",
        "Пропущено неизвестное событие воркера: %@": "Skipped an unknown worker event: %@",
        "Ожидание": "Idle",
        "Остановлено": "Stopped",
        "Ассистент не ответил: ": "The assistant did not answer: ",
        "В записи ещё нет распознанных фраз — спросите после первой.": "No phrase has been recognised yet; ask after the first one.",
        "Введите вопрос.": "Enter a question.",
        "LLM не настроена.": "LLM is not configured.",
        "Файлы с одинаковым базовым именем перезапишут результаты друг друга: %@. Переименуйте файлы или обработайте их отдельно.": "Files with the same base name would overwrite each other's results: %@. Rename them or process them separately.",
        "Воркер распознавания": "The transcription worker",
        "Live-воркер": "The live worker",
        "LLM-воркер": "The LLM worker",
        "Воркер проверки CLI": "The CLI check worker",
        "%@ не запущен.": "%@ is not running.",
        "Не удалось настроить канал ввода воркера: %@": "Could not configure the worker input pipe: %@",
        "Не удалось запустить Python проекта (%@): %@": "Could not launch the project Python (%@): %@",
        "Не удалось настроить вывод воркера: %@": "Could not configure the worker output pipe: %@",
        "%@: событие больше %@ МиБ пропущено, поэтому итог задачи неизвестен. Файлы, которые воркер успел сохранить, остались на диске.": "%@: an event larger than %@ MiB was dropped, so the outcome of this job is unknown. Files the worker already saved remain on disk.",
        "%@: не удалось прочитать вывод (%@).": "%@: could not read its output (%@).",
        "Не выбраны файлы для обработки.": "No input files supplied.",
        "Файл недоступен для чтения: %@": "Input file is not readable: %@",
        "Папка результатов должна быть локальной.": "The output folder must be a local folder.",
        "В Python-проекте нет src/tui_worker.py.": "The Python project is missing src/tui_worker.py.",
        "%@ закрыл вывод, не сообщив о завершении.": "%@ closed its output without a completion event.",
        "%@ прислал событие %@ в неверном формате.": "%@ sent an invalid %@ event.",
        "Воркер сообщил неверное число файлов.": "The worker reported a wrong number of files.",
        "Воркер прислал неверное событие завершения.": "The worker sent an invalid completion event.",
        "Воркер завершил пакет без результатов для всех файлов.": "The worker completed without results for every file.",
        "Распознавание остановилось до обработки первого файла.": "Transcription failed before processing any files.",
        "Воркер прислал ошибку без текста.": "The worker reported an error without a message.",
        "Воркер сослался на неизвестный файл.": "The worker referred to an unknown file.",
        "Воркер прислал неверный результат файла.": "The worker sent an invalid file result.",
        "Нет данных о Python-окружении.": "Missing Python runtime context.",
        "Воркер вернул недоступный или небезопасный файл результата: %@": "The worker returned an unavailable or unsafe output file: %@",
        "Транскрипт больше 32 МиБ — откройте сохранённый файл.": "The transcript is larger than the 32 MiB preview limit; open the saved file.",
        "Сохранённый транскрипт не в кодировке UTF-8.": "The saved transcript is not valid UTF-8.",
        "Python-обработчик не смог распознать этот файл.": "The Python processor could not transcribe this file.",
        "Python-обработчик не создал ни одного читаемого файла результата.": "The Python processor did not produce any readable output files.",
        "%@ завершился, не сообщив о завершении (код %@).": "%@ exited without a completion event (status %@).",
        "%@ закрыл вывод, не остановив сессию.": "%@ closed its output without stopping the session.",
        "%@ завершился, не остановив сессию (код %@).": "%@ exited without stopping the session (status %@).",
        "Ошибка Live-воркера.": "Live worker error.",
        "%@ закрыл вывод, не завершив запрос.": "%@ closed its output without completing the request.",
        "%@ завершился, не завершив запрос (код %@).": "%@ exited without completing the request (status %@).",
        "Запрос к LLM не удался.": "The LLM request failed.",
        "Ошибка LLM-воркера.": "LLM worker error.",
        "%@ закрыл вывод, не ответив.": "%@ closed its output before answering.",
        "%@ завершился, не ответив (код %@).": "%@ exited without answering (status %@).",
        "Воркер прислал неверный ответ llm_tool_check.": "The worker sent a malformed llm_tool_check reply.",
        "Проверка CLI-инструментов не удалась.": "The CLI tools check failed.",
        "Неподдерживаемый формат звука для записи.": "Unsupported audio format for live capture.",
        "GIGAAM_PROJECT_ROOT должен указывать на папку с GigaAMWorker.app или подготовленным Python-проектом.": "GIGAAM_PROJECT_ROOT must point to a folder with GigaAMWorker.app or a prepared Python project.",
        "Не найден GigaAMWorker.app или Python runtime. Задайте GIGAAM_PROJECT_ROOT для запуска из исходников.": "GigaAMWorker.app or a Python runtime was not found. Set GIGAAM_PROJECT_ROOT to run from source.",
        "Загружаем модель распознавания речи…": "Loading the speech recognition model…",
        "Готово": "Done",
        "Отменить вопрос": "Cancel question",
        "Версия приложения": "App version",
        "Не удалось сохранить HF Token": "Could not save the HF Token",
        "Выберите исполняемый файл": "Choose the executable",
        "проверка…": "checking…",
        "найден": "found",
        "не запускается": "does not start",
        "не найден": "not found",
        "Обзор…": "Browse…",
        "Проверить": "Check",
        "Установка": "Install",
        "произвольная команда": "custom command",
        "Пересканировать": "Rescan",
        "Инструменты": "Tools",
        "Пустой путь — автопоиск по PATH и типичным каталогам (homebrew, npm, bun, nvm). Приложение из Finder не видит PATH терминала — поиск ведёт Python-сервис.": "An empty path searches PATH and the usual folders (homebrew, npm, bun, nvm). An app opened from Finder does not see the terminal's PATH, so the Python service does the search.",
        "Дополнительные параметры": "Additional options",
        "Обычно не нужны — всё работает с пустыми полями. «Аргументы» — флаги командной строки, которые добавляются к запуску CLI как есть (как в терминале): например, уровень рассуждений или профиль. «Provider» у Pi и oh-my-pi — внутренний поставщик модели (anthropic, openai, google…), если нужно переопределить настроенный в самом CLI. Модель берётся из общего поля «Модель» выше.": "Usually not needed: everything works with empty fields. “Arguments” are command-line flags added to the CLI as is (as in a terminal), for example a reasoning level or a profile. “Provider” for Pi and oh-my-pi is the model vendor inside the CLI (anthropic, openai, google…), to override the one configured in the CLI itself. The model comes from the shared Model field above.",
        "Флаги командной строки, добавляются к запуску как есть. Пример: ": "Command-line flags, added to the command as is. Example: ",
        "%@ — аргументы": "%@ — arguments",
        "по умолчанию из конфига CLI": "default from the CLI config",
        "Внутренний поставщик модели: anthropic, openai, google, openrouter… Пусто — как настроено в ": "The model vendor inside the CLI: anthropic, openai, google, openrouter… Empty means as configured in ",
        "%@ — поставщик модели": "%@ — model provider",
        "«Другое» — любая своя команда. Промпт передаётся последним аргументом и одновременно в stdin; напишите {stdin} в аргументах, чтобы передавать только через stdin. Ответ читается из stdout.": "“Other” is any command of your own. The prompt is passed as the last argument and on stdin; write {stdin} in the arguments to pass it on stdin only. The answer is read from stdout.",
        "Другое — команда": "Other — command",
        "Другое — аргументы": "Other — arguments",
        "Разрешить инструменты и сессии агента": "Allow agent tools and sessions",
        "Выключено: claude/codex/opencode/pi/omp запускаются как чистый запрос к модели — без доступа к файлам и без записи в историю сессий агента.": "Off: claude/codex/opencode/pi/omp run as a plain model request, with no file access and nothing written to the agent's session history.",
        "Выключено — CLI работает как чистый запрос к модели: агент не читает файлы и не сохраняет сессию. Включайте, только если хотите, чтобы он мог пользоваться своими инструментами. Ключ API хранится в Связке ключей.": "Off: the CLI runs as a plain model request; the agent reads no files and keeps no session. Turn it on only if you want it to use its own tools. The API key is stored in the Keychain.",
        "Связка ключей недоступна": "Keychain unavailable",
        "Не удалось прочитать HF Token из Связки ключей: %@": "Could not read the HF Token from the Keychain: %@",
        "Не удалось прочитать API Key из Связки ключей: %@": "Could not read the API Key from the Keychain: %@",
        "Пропущено фрагментов звука по 100 мс: %@.": "Dropped 100 ms audio chunks: %@."
    ]
}
