//! Сгенерировано scripts/tui/gen_theme_catalog.py — не править руками.
//!
//! Палитры oh-my-pi (MIT, см. tui/themes/LICENSE-oh-my-pi) и наши собственные
//! JSON из tui/themes/, вшитые в бинарник; имя = имя файла без `.json`.

/// `("<имя>", include_str!("../themes/<имя>.json"))` — короткая строка на тему,
/// которую rustfmt не переносит, что бы ни менялось в его эвристиках ширины.
macro_rules! theme {
    ($name:literal) => {
        ($name, include_str!(concat!("../themes/", $name, ".json")))
    };
}

/// Пары «имя темы → JSON», отсортированные по имени.
pub(crate) static THEMES: &[(&str, &str)] = &[
    theme!("alabaster"),
    theme!("amethyst"),
    theme!("anthracite"),
    theme!("basalt"),
    theme!("birch"),
    theme!("dark-abyss"),
    theme!("dark-arctic"),
    theme!("dark-aurora"),
    theme!("dark-catppuccin"),
    theme!("dark-cavern"),
    theme!("dark-celestial"),
    theme!("dark-copper"),
    theme!("dark-cosmos"),
    theme!("dark-cyberpunk"),
    theme!("dark-dracula"),
    theme!("dark-eclipse"),
    theme!("dark-ember"),
    theme!("dark-equinox"),
    theme!("dark-forest"),
    theme!("dark-github"),
    theme!("dark-gruvbox"),
    theme!("dark-hermes-pink"),
    theme!("dark-lavender"),
    theme!("dark-lunar"),
    theme!("dark-midnight"),
    theme!("dark-monochrome"),
    theme!("dark-monokai"),
    theme!("dark-nebula"),
    theme!("dark-nord"),
    theme!("dark-ocean"),
    theme!("dark-one"),
    theme!("dark-poimandres"),
    theme!("dark-rainforest"),
    theme!("dark-reef"),
    theme!("dark-retro"),
    theme!("dark-rose-pine"),
    theme!("dark-sakura"),
    theme!("dark-slate"),
    theme!("dark-solarized"),
    theme!("dark-solstice"),
    theme!("dark-starfall"),
    theme!("dark-sunset"),
    theme!("dark-swamp"),
    theme!("dark-synthwave"),
    theme!("dark-taiga"),
    theme!("dark-terminal"),
    theme!("dark-tokyo-night"),
    theme!("dark-tundra"),
    theme!("dark-twilight"),
    theme!("dark-volcanic"),
    theme!("graphite"),
    theme!("light-arctic"),
    theme!("light-aurora-day"),
    theme!("light-canyon"),
    theme!("light-catppuccin"),
    theme!("light-cirrus"),
    theme!("light-coral"),
    theme!("light-cyberpunk"),
    theme!("light-dawn"),
    theme!("light-dunes"),
    theme!("light-eucalyptus"),
    theme!("light-forest"),
    theme!("light-frost"),
    theme!("light-github"),
    theme!("light-glacier"),
    theme!("light-gruvbox"),
    theme!("light-haze"),
    theme!("light-honeycomb"),
    theme!("light-lagoon"),
    theme!("light-lavender"),
    theme!("light-meadow"),
    theme!("light-mint"),
    theme!("light-monochrome"),
    theme!("light-ocean"),
    theme!("light-one"),
    theme!("light-opal"),
    theme!("light-orchard"),
    theme!("light-paper"),
    theme!("light-poimandres"),
    theme!("light-prism"),
    theme!("light-retro"),
    theme!("light-sand"),
    theme!("light-savanna"),
    theme!("light-solarized"),
    theme!("light-soleil"),
    theme!("light-sunset"),
    theme!("light-synthwave"),
    theme!("light-tokyo-night"),
    theme!("light-wetland"),
    theme!("light-zenith"),
    theme!("limestone"),
    theme!("mahogany"),
    theme!("marble"),
    theme!("obsidian"),
    theme!("onyx"),
    theme!("pearl"),
    theme!("porcelain"),
    theme!("quartz"),
    theme!("sandstone"),
    theme!("titanium"),
];
