"""Сгенерировать LogTranslation.swift из src/core/log_i18n.py.

GigaAMLiquid переводит журнал обработки той же таблицей, что и PyQt. Таблица
живёт в Python; Swift-копия генерируется, а
tests/test_processing_log_messages.py проверяет, что она не устарела:

    python scripts/gen_log_translation_swift.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.core.log_i18n import LOG_TRANSLATIONS  # noqa: E402

TARGET = ROOT / "macos/GigaAMLiquid/Sources/GigaAMLiquidCore/LogTranslation.swift"

HEADER = '''// Generated by scripts/gen_log_translation_swift.py from src/core/log_i18n.py.
// Do not edit by hand: run the script and commit both files together.
import Foundation

/// English rendering of the Russian processing log, one line at a time.
/// Rules are tried in order; captured groups are translated recursively so
/// "  Почему: <причина>" becomes "  Why: <reason>" while file names and
/// exception text pass through unchanged.
public enum LogTranslation {
    static let rules: [(NSRegularExpression, String)] = [
'''

FOOTER = '''    ].map { (try! NSRegularExpression(pattern: $0.0), $0.1) }

    private static let groupReference = try! NSRegularExpression(pattern: #"\\$(\\d)"#)

    public static func english(_ line: String) -> String {
        let range = NSRange(line.startIndex..., in: line)
        for (pattern, template) in rules {
            guard let match = pattern.firstMatch(in: line, range: range) else { continue }
            var groups: [String] = []
            for index in 1..<max(1, match.numberOfRanges) {
                let groupRange = match.range(at: index)
                if groupRange.location == NSNotFound { groups.append(""); continue }
                let text = String(line[Range(groupRange, in: line)!])
                groups.append(text.isEmpty ? "" : english(text))
            }
            var output = template
            let matches = groupReference.matches(in: template, range: NSRange(template.startIndex..., in: template))
            for reference in matches.reversed() {
                let number = Int(template[Range(reference.range(at: 1), in: template)!])!
                let replacement = groups.indices.contains(number - 1) ? groups[number - 1] : ""
                output.replaceSubrange(Range(reference.range, in: output)!, with: replacement)
            }
            return output
        }
        return line
    }

    /// Multi-line messages (error details) are translated line by line.
    public static func englishText(_ text: String) -> String {
        text.split(separator: "\\n", omittingEmptySubsequences: false).map { english(String($0)) }.joined(separator: "\\n")
    }
}
'''


def render() -> str:
    rows = []
    for pattern, template in LOG_TRANSLATIONS:
        assert '"#' not in pattern, pattern
        swift_template = re.sub(r"\\(\d)", r"$\1", template).replace("\\", "\\\\").replace('"', '\\"')
        rows.append(f'        (#"{pattern}"#, "{swift_template}"),')
    return HEADER + "\n".join(rows) + "\n" + FOOTER


def main() -> int:
    content = render()
    if "--check" in sys.argv:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != content:
            print(f"{TARGET} is out of date; run python scripts/gen_log_translation_swift.py", file=sys.stderr)
            return 1
        return 0
    TARGET.write_text(content, encoding="utf-8")
    print(f"wrote {TARGET} ({len(LOG_TRANSLATIONS)} rules)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
