// Generated by scripts/gen_log_translation_swift.py from src/core/log_i18n.py.
// Do not edit by hand: run the script and commit both files together.
import Foundation

/// English rendering of the Russian processing log, one line at a time.
/// Rules are tried in order; captured groups are translated recursively so
/// "  Почему: <причина>" becomes "  Why: <reason>" while file names and
/// exception text pass through unchanged.
public enum LogTranslation {
    static let rules: [(NSRegularExpression, String)] = [
        (#"^Загружаем модель распознавания речи…$"#, "Loading the speech recognition model…"),
        (#"^Подготавливаем модель распознавания речи \(GigaAM-v3\)…$"#, "Preparing the speech recognition model (GigaAM-v3)…"),
        (#"^Загружаем модель для Apple Silicon \(MLX\): (.+)$"#, "Loading the Apple Silicon (MLX) model: $1"),
        (#"^При первом запуске модель скачивается — это может занять несколько минут\.$"#, "The model is downloaded on first launch; this can take a few minutes."),
        (#"^Движок распознавания: (.+)$"#, "Recognition engine: $1"),
        (#"^Вычисления выполняются на устройстве: (.+)$"#, "Computing on: $1"),
        (#"^Модель готова\.$"#, "Model ready."),
        (#"^Модель готова \(ONNX, (.+?)\); вычисления выполняются на: (.+)$"#, "Model ready (ONNX, $1); computing on: $2"),
        (#"^Модель загружена\.$"#, "Model loaded."),
        (#"^Не удалось загрузить модель распознавания \(ONNX\):(.*)$"#, "Could not load the speech recognition model (ONNX):$1"),
        (#"^Не удалось загрузить модель распознавания:(.*)$"#, "Could not load the speech recognition model:$1"),
        (#"^Не удалось загрузить модель распознавания$"#, "Could not load the speech recognition model"),
        (#"^Не удалось загрузить модель MLX \((.+?)\): (.+)$"#, "Could not load the MLX model ($1): $2"),
        (#"^Не удалось загрузить модель через движок (.+)$"#, "Could not load the model with the $1 engine"),
        (#"^Не удалось запустить движок распознавания: (.+)$"#, "Could not start the recognition engine: $1"),
        (#"^Не удалось выбрать движок распознавания для загрузки модели$"#, "Could not pick a recognition engine to load the model"),
        (#"^Файл (\d+) из (\d+): (.+)$"#, "File $1 of $2: $3"),
        (#"^Длительность записи: неизвестна$"#, "Recording length: unknown"),
        (#"^Длительность записи: (.+)$"#, "Recording length: $1"),
        (#"^Файл: (.+)$"#, "File: $1"),
        (#"^Файл пропущен: (.+)$"#, "File skipped: $1"),
        (#"^Подготавливаем звук: (.+) → WAV 16 кГц…$"#, "Preparing audio: $1 → 16 kHz WAV…"),
        (#"^Звук подготовлен\.$"#, "Audio prepared."),
        (#"^Подготовка звука заняла слишком долго и была прервана — файл не обработан\.$"#, "Audio preparation took too long and was stopped; the file was not processed."),
        (#"^FFmpeg не смог подготовить звук \(код ошибки (\d+)\)\. Подробности ниже:$"#, "FFmpeg could not prepare the audio (error code $1). Details below:"),
        (#"^  FFmpeg: (.*)$"#, "  FFmpeg: $1"),
        (#"^Возможная причина: файл повреждён или загружен не до конца.*$"#, "Likely cause: the file is damaged or was not fully downloaded (MP4 keeps its «moov» metadata at the end; a truncated file cannot be read by FFmpeg)."),
        (#"^Что попробовать: перезаписать/скачать файл заново.*$"#, "What to try: re-download or re-save the file, open it in another player and export it again, or use a different file."),
        (#"^Ошибка: не найдена программа FFmpeg .*$"#, "Error: FFmpeg was not found (neither in the app nor on the system); audio cannot be prepared without it."),
        (#"^Ошибка: не удалось запустить FFmpeg \((.+)\)\.$"#, "Error: could not start FFmpeg ($1)."),
        (#"^Проверьте, что рядом с приложением нет несовместимого ffmpeg.*$"#, "Make sure there is no incompatible ffmpeg for another OS/architecture next to the app."),
        (#"^Ошибка: файл не найден: (.+)$"#, "Error: file not found: $1"),
        (#"^Ошибка: это не файл, а папка или другой объект: (.+)$"#, "Error: not a file (a folder or another object): $1"),
        (#"^Очистка звука: (.+) \(режим (.+)\)$"#, "Audio cleanup: $1 (mode $2)"),
        (#"^Очистка звука не выполнялась: (.+) \(режим (.+)\)$"#, "Audio cleanup skipped: $1 (mode $2)"),
        (#"^  Почему: (.+)$"#, "  Why: $1"),
        (#"^  Очистка не применена: (.+)$"#, "  Cleanup not applied: $1"),
        (#"^Очистка звука недоступна, используем запись как есть: (.+)$"#, "Audio cleanup unavailable; using the recording as is: $1"),
        (#"^не требуется$"#, "not needed"),
        (#"^лёгкая очистка от шума$"#, "light noise cleanup"),
        (#"^нейросетевое подавление шума$"#, "neural noise suppression"),
        (#"^выравнивание громкости$"#, "loudness normalisation"),
        (#"^речь слабо выделяется на фоне шума$"#, "speech barely stands out from the noise"),
        (#"^в записи постоянный фоновый шум$"#, "constant background noise in the recording"),
        (#"^в записи низкочастотный гул$"#, "low-frequency rumble in the recording"),
        (#"^в записи сильный фоновый шум$"#, "heavy background noise in the recording"),
        (#"^нейросетевая очистка недоступна, применена мягкая очистка FFmpeg$"#, "neural cleanup unavailable; gentle FFmpeg cleanup applied"),
        (#"^запись сильно перегружена \(клиппинг\), очистка не поможет$"#, "the recording is heavily clipped; cleanup would not help"),
        (#"^в записи почти нет речи, очистка не выполнялась$"#, "almost no speech in the recording; cleanup skipped"),
        (#"^запись тихая, но усиливать её небезопасно$"#, "the recording is quiet, but amplifying it is unsafe"),
        (#"^речь тихая, но чистая — громкость выровнена$"#, "speech is quiet but clean; loudness normalised"),
        (#"^запись чистая, очистка не нужна$"#, "the recording is clean; no cleanup needed"),
        (#"^очистка звука отключена в настройках$"#, "audio cleanup is disabled in settings"),
        (#"^лёгкая очистка выбрана в настройках$"#, "light cleanup selected in settings"),
        (#"^нейросетевая очистка выбрана в настройках$"#, "neural cleanup selected in settings"),
        (#"^средство очистки завершилось с ошибкой, использована исходная запись$"#, "the cleanup tool failed; the original recording was used"),
        (#"^результат очистки отклонён: (.+)$"#, "cleanup result rejected: $1"),
        (#"^не удалось проверить результат очистки: (.+)$"#, "could not verify the cleanup result: $1"),
        (#"^после очистки появились перегрузки$"#, "clipping appeared after cleanup"),
        (#"^очистка заглушила часть речи$"#, "cleanup silenced part of the speech"),
        (#"^после очистки речь стала слишком тихой$"#, "speech became too quiet after cleanup"),
        (#"^громкость ушла от нужного уровня$"#, "loudness drifted from the target"),
        (#"^очистка не дала заметного улучшения$"#, "cleanup brought no measurable improvement"),
        (#"^Распознаём речь…$"#, "Recognizing speech…"),
        (#"^Речь найдена: участков — (\d+), фрагментов для распознавания — (\d+)$"#, "Speech found: $1 region(s), $2 fragment(s) to recognize"),
        (#"^Распознавание завершено: фрагментов текста — (\d+)$"#, "Recognition finished: $1 text fragment(s)"),
        (#"^Не удалось найти речь в записи \(ошибка детектора речи\): (.+)$"#, "Could not find speech in the recording (speech detector error): $1"),
        (#"^Ошибка при распознавании речи: (.+)$"#, "Speech recognition error: $1"),
        (#"^Реплик в тексте: (\d+)$"#, "Utterances in the text: $1"),
        (#"^Внимание: фрагмент (.+) распознан без текста$"#, "Warning: fragment $1 was recognized without text"),
        (#"^Внимание: речь не распознана — все фрагменты пустые$"#, "Warning: no speech recognized; every fragment is empty"),
        (#"^Внимание: распознанный текст пуст$"#, "Warning: the recognized text is empty"),
        (#"^Внимание: в файле (.+) не найдено речи\.$"#, "Warning: no speech found in $1."),
        (#"^Внимание: говорящих определить не удалось, файл (.+) не создан$"#, "Warning: speakers could not be identified; $1 was not created"),
        (#"^Возможные причины:$"#, "Possible reasons:"),
        (#"^  1\. В записи нет речи или она очень тихая$"#, "  1. The recording has no speech, or it is very quiet"),
        (#"^  2\. Не работает токен HuggingFace для pyannote/segmentation-3\.0$"#, "  2. The HuggingFace token for pyannote/segmentation-3.0 does not work"),
        (#"^  3\. Не удалось разбить запись на участки речи$"#, "  3. The recording could not be split into speech regions"),
        (#"^Проверьте токен HF_TOKEN и убедитесь, что приняли условия доступа:$"#, "Check the HF_TOKEN and make sure you accepted the access terms:"),
        (#"^Проверьте токен HF_TOKEN в \.env файле и убедитесь, что приняли условия доступа:$"#, "Check the HF_TOKEN in the .env file and make sure you accepted the access terms:"),
        (#"^Внимание: определение говорящих переключилось на запасной режим — (.+)$"#, "Warning: speaker identification switched to a fallback mode — $1"),
        (#"^Внимание: (.+)$"#, "Warning: $1"),
        (#"^VAD пропустил длинный участок с активным звуком; использовано полное разбиение по тихим точкам с перекрытием$"#, "VAD skipped a long stretch of active audio; full silence-based splitting with overlap was used"),
        (#"^VAD недоступен \((.+?)\): (?:проверьте локальный кэш или HF_TOKEN и доступ к pyannote/segmentation-3\.0; )?использовано резервное разбиение по тихим точкам с перекрытием$"#, "VAD unavailable ($1): check the local cache or HF_TOKEN and access to pyannote/segmentation-3.0; fallback silence-based splitting with overlap was used"),
        (#"^ONNX VAD недоступен \((.+?)\); использовано разбиение по тихим точкам с перекрытием$"#, "ONNX VAD unavailable ($1); silence-based splitting with overlap was used"),
        (#"^VAD отключён настройкой ASR_SEGMENTATION_MODE: использовано разбиение по тихим точкам с перекрытием$"#, "VAD disabled by ASR_SEGMENTATION_MODE: silence-based splitting with overlap was used"),
        (#"^VAD отключён настройкой ASR_SEGMENTATION_MODE: использовано legacy-разбиение по 20 секунд без перекрытия$"#, "VAD disabled by ASR_SEGMENTATION_MODE: legacy 20-second splitting without overlap was used"),
        (#"^VAD отключён настройкой: использовано разбиение по тихим точкам с перекрытием$"#, "VAD disabled in settings: silence-based splitting with overlap was used"),
        (#"^VAD отключён настройкой: использовано разбиение по 20 секунд$"#, "VAD disabled in settings: 20-second splitting was used"),
        (#"^(.+?) завершил inference с ошибкой (.+?); транскрибация начата заново на CPUExecutionProvider, прогресс отсчитывается с нуля$"#, "$1 failed during inference ($2); recognition restarted on CPUExecutionProvider, progress starts over"),
        (#"^Аварийный fallback: (.+?) не загрузился, использован PyTorch backend$"#, "Emergency fallback: $1 failed to load; the PyTorch engine was used"),
        (#"^Определяем, кто говорит \((.+)\)…$"#, "Identifying speakers ($1)…"),
        (#"^Определение говорящих выполняется на: (.+)$"#, "Speaker identification runs on: $1"),
        (#"^устройство (.+?), провайдер (.+)$"#, "device $1, provider $2"),
        (#"^устройство (.+)$"#, "device $1"),
        (#"^провайдер (.+)$"#, "provider $1"),
        (#"^Говорящих найдено: (\d+)$"#, "Speakers found: $1"),
        (#"^Не удалось определить говорящих, текст сохранён без разметки по говорящим: (.+)$"#, "Could not identify speakers; the text was saved without speaker labels: $1"),
        (#"^Не удалось подготовить определение говорящих: (.+)$"#, "Could not set up speaker identification: $1"),
        (#"^Ошибка при определении говорящих: (.+)$"#, "Speaker identification error: $1"),
        (#"^Частая причина: на huggingface\.co не приняты условия ВСЕХ моделей —$"#, "Common cause: the terms of ALL models were not accepted on huggingface.co —"),
        (#"^либо у токена нет права read\.$"#, "or the token lacks read permission."),
        (#"^Причина указана выше\.$"#, "The reason is above."),
        (#"^Укажите токен в настройках диаризации \(определения говорящих\)\.$"#, "Set the token in the diarization (speaker identification) settings."),
        (#"^Ошибка: (.+)$"#, "Error: $1"),
        (#"^Объём текста: (\d+) символов$"#, "Text size: $1 characters"),
        (#"^Сохранён файл: (.+)$"#, "Saved file: $1"),
        (#"^Готово за (.+?) \(подготовка звука (.+?) с, распознавание (.+?) с\)$"#, "Done in $1 (audio preparation $2 s, recognition $3 s)"),
        (#"^(\d+) ч (\d+) мин$"#, "$1 h $2 min"),
        (#"^(\d+) мин (\d+) сек$"#, "$1 min $2 s"),
        (#"^(\d+) сек$"#, "$1 s"),
        (#"^Не удалось обработать (.+?): (.+)$"#, "Could not process $1: $2"),
        (#"^Остановка запрошена: закончим текущий файл и остановимся\.$"#, "Stop requested: finishing the current file, then stopping."),
    ].map { (try! NSRegularExpression(pattern: $0.0), $0.1) }

    private static let groupReference = try! NSRegularExpression(pattern: #"\$(\d)"#)

    public static func english(_ line: String) -> String {
        let range = NSRange(line.startIndex..., in: line)
        for (pattern, template) in rules {
            guard let match = pattern.firstMatch(in: line, range: range) else { continue }
            var groups: [String] = []
            for index in 1..<max(1, match.numberOfRanges) {
                let groupRange = match.range(at: index)
                if groupRange.location == NSNotFound { groups.append(""); continue }
                let text = String(line[Range(groupRange, in: line)!])
                groups.append(text.isEmpty ? "" : english(text))
            }
            var output = template
            let matches = groupReference.matches(in: template, range: NSRange(template.startIndex..., in: template))
            for reference in matches.reversed() {
                let number = Int(template[Range(reference.range(at: 1), in: template)!])!
                let replacement = groups.indices.contains(number - 1) ? groups[number - 1] : ""
                output.replaceSubrange(Range(reference.range, in: output)!, with: replacement)
            }
            return output
        }
        return line
    }

    /// Multi-line messages (error details) are translated line by line.
    public static func englishText(_ text: String) -> String {
        text.split(separator: "\n", omittingEmptySubsequences: false).map { english(String($0)) }.joined(separator: "\n")
    }
}
